# Generated by Django 4.2.7 on 2023-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='additions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
