# Generated by Django 4.2.7 on 2023-11-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_alter_pizza_additions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzeria',
            name='additions',
        ),
        migrations.DeleteModel(
            name='Addition',
        ),
        migrations.AddField(
            model_name='pizzatopping',
            name='pizzeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizzeria'),
        ),
        migrations.AddField(
            model_name='pizzatopping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.topping'),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='toppings',
            field=models.ManyToManyField(blank=True, through='pizzeria.PizzaTopping', to='pizzeria.topping'),
        ),
    ]
